const Policy = () => {
    return (
        <section className="Policy">
            <br/>

                <h3>Thank you for using our services! This Privacy Policy describes:</h3>
                <br/>

                    <br/>

                        • The ways we collect personal data about you and why we do so.
                        <br/>

                            • How we use your personal data.
                            <br/>

                                • The choices you have about your personal data.
                                <br/>

                                    <br/>

                                        This Privacy Policy applies to DRYGON's games, websites and related services, which we here refer to as the Service. We may periodically update this Privacy Policy. If we make any changes, we will notify you by posting a notice in the news on the DRYGON website.
                                        <br/>

                                            <br/>

                                                <h3>CONTACT US</h3>
                                                <br/>

                                                    <br/>

                                                        If you have questions about data protection, or if you have any requests for resolving issues with your personal data, we encourage you to primarily contact us by E-mail, so we can reply to you more quickly.
                                                        <br/>

                                                            E-mail: team.drygon@gmail.com
                                                            <br/>

                                                                <br/>

                                                                    <h3>THE DATA WE COLLECT</h3>
                                                                    <br/>

                                                                        <br/>

                                                                            <h5>Data you provide us.</h5>
                                                                            <br/>

                                                                                <br/>

                                                                                    The Information provided won’t be used in any way that would cause you or anyone related to you trouble.
                                                                                    <br/>

                                                                                        • Contact information (such as name and email address)
                                                                                        <br/>

                                                                                            • Player name and password
                                                                                            <br/>

                                                                                                • Profile information (such as profile photo)
                                                                                                <br/>

                                                                                                    • Your messages to the Service (such as chat logs and
                                                                                                    <br/>

                                                                                                        player support tickets)
                                                                                                        <br/>

                                                                                                            • Other data you choose to give us (such as data to identify a lost account)
                                                                                                            <br/>

                                                                                                                <br/>

                                                                                                                    <h5>Data we collect automatically.</h5>
                                                                                                                    <br/>

                                                                                                                        <br/>

                                                                                                                            • Data about your account and game progress
                                                                                                                            <br/>

                                                                                                                                • Your IP address and mobile device identifiers (such as your device ID, advertising ID, MAC address, IMEI)
                                                                                                                                <br/>

                                                                                                                                    • Data about your device, such as device name and operating system, browser type and language
                                                                                                                                    <br/>

                                                                                                                                        <br/>

                                                                                                                                            <h5>Data we collect with cookies and similar technologies (see more below)</h5>
                                                                                                                                            <br/>

                                                                                                                                                <br/>

                                                                                                                                                    • Data about your use of the Service, such as gameplay data and your interactions with
                                                                                                                                                    <br/>

                                                                                                                                                        other players inside the Service

                                                                                                                                                        • In most cases, we also create a DRYGON-specific ID for you when you use the
                                                                                                                                                        <br/>

                                                                                                                                                            Service. (For every person is unique and it will make your account safe to other users)
                                                                                                                                                            <br/>

                                                                                                                                                                <br/>

                                                                                                                                                                    <h5>Data we collect from our partners.</h5>
                                                                                                                                                                    <br/>

                                                                                                                                                                        <br/>

                                                                                                                                                                            • Data we receive if you link a third-party tool with the Service (such as Facebook,
                                                                                                                                                                            <br/>

                                                                                                                                                                                WeChat or Google)

                                                                                                                                                                                • Demographic data (such as to determine the coarse location of your IP address)
                                                                                                                                                                                <br/>

                                                                                                                                                                                    • Data to fight fraud (such as refund abuse in games or click fraud in advertising)
                                                                                                                                                                                    <br/>

                                                                                                                                                                                        • Data from platforms that the games run on (such as to verify payment)
                                                                                                                                                                                        <br/>

                                                                                                                                                                                            • Data for advertising and analytics purposes, so we can provide you a better Service
                                                                                                                                                                                            <br/>

                                                                                                                                                                                                <br/>

                                                                                                                                                                                                    <h3>WHY DO WE COLLECT YOUR DATA</h3>
                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                            • To perform the contract, we process data necessary to
                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                • Create accounts and allow you to play our games and use our Service
                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                    • Operate the Service
                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                        • Verify and confirm payments
                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                            • Provide and deliver products and services you request
                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                • Send you Service-related communications
                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                    • To make the Service more suitable for our players.
                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                        • Develop and improve the Service and player experience
                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                            • Manage our relationship with you
                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                • Provide social features as part of the Service
                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                    • Respond to your comments and questions and provide player support
                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                        • Send you related information, such as updates, security alerts, and support messages
                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                            • Enable you to communicate with other players
                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                • To show personalized advertisements.
                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                    • Track the content you access in connection with the Service and your online behavior
                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                        • Deliver, target and improve our advertising and the Service.
                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                            • For information on how to opt-out from personalized advertisements, see section 'Your rights and options' below.
                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                • To keep the Service safe and fair.
                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                    • Ensuring a level playing field in the Service is a top priority for us. For more information on our acceptable use policy, see the Supercell Terms of Service.
                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                        • In order to keep the Service and its social features safe and fair, to fight fraud and ensure acceptable use otherwise, we have a legitimate interest to process necessary data to
                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                            • Analyze and monitor use of the Service and its social features
                                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                                • Moderate chats either automatically or manually
                                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                                    • Take action against fraudulent or misbehaving players
                                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                                        • To analyze, profile, and segment.
                                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                                            • In all of the above cases and purposes, we may analyze, profile and segment all collected data.
                                                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                                                    With your consent, we may process your data for additional purposes, such as using your GPS location to show your local events.
                                                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                                                            <h3>WHO CAN SEE YOUR DATA Apart from DRYGON</h3>
                                                                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                                                                    <h5>Other players and users.</h5>
                                                                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                                                                            Social features are a core component of our games. Other players and users may, for example, see your profile data, in-game activities and read the messages you have posted. Note that nothing Personal outside of the player username and information regarding to the character isn't visible to the public eye.
                                                                                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                                                                                    <h3>PARTNERS WORKING FOR DRYGON.</h3>
                                                                                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                                                                                            DRYGON has partners to perform services for us.
                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                    These partners process your data only at and according to
                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                            In order to combat fraud and illegal activity, we may exchange data with other companies and organizations and provide it to public authorities in response to lawful requests.
                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                    We may also disclose your data based on your consent, to comply with the law or to protect the rights, property or safety of us, our players or others.
                                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                            Advertising and Social Media partners.
                                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                                    The Service includes features from our partners, such as social media interaction tools and in-game advertising.  These partners may access your data and operate under their own privacy policies.
                                                                                                                                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                                                                                                                                            <h3>INTERNATIONAL DATA TRANSFERS</h3>
                                                                                                                                                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                    Our Service is global by nature and your data can therefore be transferred to anywhere in the world. Because different countries may have different data protection laws than your own country, we take steps to ensure adequate safeguards are in place to protect your data as explained in this Policy.
                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                            Adequate safeguards that our partners may use include standard contractual clauses approved by EU Commission and the Privacy Shield certification in case of transfers to the USA.
                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>YOUR RIGHTS AND OPTIONS</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                            <h5>Opt-out of marketing emails and other direct marketing.</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    You may opt-out of receiving promotional communications, such as marketing emails from us by following the instructions in such communications.
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h5>Opt-out of targeted advertising.</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    You can opt-out of interest-based advertising on mobile applications by checking the privacy settings of your Android or iOS device and selecting "limit ad tracking" (Apple iOS) or "opt-out of interest-based ads" (Android).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            For personalized in-game offers opt-out, you can use the options provided in the game settings.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Access the personal data we hold about you.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If you request, we will provide you a copy of your personal data in an electronic format.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h5>Your other rights.</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            You also have the right to correct your data, have your data deleted, object how we use or share your data, and restrict how we use or share your data. You can always withdraw your consent, for example by turning off GPS location sharing in your mobile device settings.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h5>We will respond to all requests within a reasonable timeframe.</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            If you have an unresolved privacy or data use concern that we have not addressed satisfactorily, please contact our U.S.-based third-party dispute resolution provider (free of charge).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    You may also contact your local data protection authority within the European Economic Area for unresolved complaints.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>COOKIES AND SIMILAR TECHNOLOGIES</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Like most online services, we and our partners use cookies and similar technologies to provide and personalize the Service, analyze use, target advertisements and prevent fraud. You can disable cookies in your browser settings, but some parts of the Service may then not function properly.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>HOW DO WE PROTECT YOUR DATA</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h5>Security Safeguards.</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            In order to help ensure a secure and safe player experience, we are continuously developing and implementing administrative, technical and physical security measures to protect your data from unauthorized access or against loss, misuse or alteration.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h5>Data retention.</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            We retain your data for as long as your account is active or as needed to provide you the Service. We will for example periodically de-identify unused game accounts and we regularly review and de-identify unnecessary data.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Note that if you ask us to remove your personal data, we will retain your data as necessary for our legitimate business interests, such as to comply with our legal obligations, resolve disputes, and enforce our agreements.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>AGE LIMITS</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    We do not knowingly collect or solicit personal data about or direct or target interest-based advertising to anyone under the age of 13 or knowingly allow such people to use our Services.  If you are under 13, please do not send any data about yourself to us, including your name, address, telephone number, or email address.  No one under the age of 13 may provide any personal data. Unless you have the permission from your guardian. If we learn that we have collected personal data about a child under the age of 13, which has no permission from its guardian, we will delete that data as quickly as possible.  If you believe that we might have any data from or about a child under the age of 13, please contact us.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    We will look in to it as soon as we get the needed information.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h5>Last edited: April 16, 2021</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
};

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Policy;
